; homez.g
; called to home the Z axis
M561    ;取消床网补偿;
; generated by RepRapFirmware Configuration Tool v3.2.1 on Sun Jun 06 2021 01:37:39 GMT+0800 (中国标准时间)
G91              ; relative positioning
G1 H2 Z5 F6000   ; lift Z relative to current position
G90              ; absolute positioning
M98 P"/sys/config/Z_homing_sensor_coordinates.g"
G91
G1 H1 Z-300 F400
G1 Z3.5 F400
G1 H1 Z-100 F150
M98 P"/sys/config/Z_offset_homez.g"
G0 Z10
G90
G0 X0 Y0 F12000

