; homex.g
; called to home the X axis
;

; generated by RepRapFirmware Configuration Tool v3.2.1 on Sun Jun 06 2021 01:37:39 GMT+0800 (中国标准时间)
G91               ; relative positioning
G1 H2 Z5 F6000    ; lift Z relative to current position
G1 H1 X-305 F12000  
G1 X5 F12000      ; go back a few mm
G1 H1 X-305 F200  ; move slowly to X axis endstop once more (second
G1 H2 Z-5 F6000   ; lower Z again
G90               ; absolute positioning


